(ns task-tracker.task-tracker.tasks.rpg.icespire-peak)
(def tasks
  [[1 "Young White Dragon" :rpg/mini 2]
   [6 "Stirg" :rpg/mini 2]
   [8 "Giant Spider" :rpg/mini 2]
   [1 "Banshee" :rpg/mini 5]
   [10 "Dwarf Ghouls" :rpg/mini 2]
   [4 "Riding Horses" :rpg/mini 2]
   [20 "Orcs" :rpg/mini 2]
   [4 "Anchorite (Half Orc Shape-shifter)" :rpg/mini 2]
   [2 "Mimic" :rpg/mini 3]
   [20 "Rock Gnome" :rpg/mini 2]
   [8 "Ankheg" :rpg/mini 2]
   [9 "Twig Blight" :rpg/mini 2]
   [4 "Needle Blight" :rpg/mini 2]
   [6 "Were Rats" :rpg/mini 2]
   [6 "Giant Rats" :rpg/mini 2]
   [5 "Dwarven Miner" :rpg/mini 2]
   [1 "Carrion Crawler" :rpg/mini 2]
   [4 "Ogres" :rpg/mini 2]
   [3 "Will-o-wisp" :rpg/mini 3]
   [1 "Invisible Stalker" :rpg/mini 3]
   [4 "Boar" :rpg/mini 3]
   [4 "Harpies" :rpg/mini 2]
   [1 "Giant Crab" :rpg/mini 3]
   [3 "Hunter Sharks" :rpg/mini 2]
   [4 "Vine Blights" :rpg/mini 2]
   [2 "Ocre Jelly" :rpg/mini 2]
   [4 "Ballistas" :rpg/mini 3]
   [1 "Ballista Platform" :rpg/mini 2]
   [1 "Big Al [Human]" :rpg/mini 2]
   [1 "Thunder Boar" :rpg/mini 2]
   [1 "Barrel Crab Mech" :rpg/mini-fab 2]
   [1 "Don Jon Raskin" :rpg/mini 2]
   [1 "Centaur" :rpg/mini 2]
   [1 "Skeletal Horse" :rpg/mini 2]]
  )
